#! /bin/sh

### BEGIN INIT INFO
# Provides:        firewall
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start Hardening Firewall
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start|restart|force-reload)
        /usr/local/bin/firewall/firewall
        exit $?
        ;;
  stop)
        /usr/local/bin/firewall/firewall stop
        exit $?
        ;;
  *)
        echo "Usage: /etc/init.d/firewall" \
                        "{start|stop}"
        exit 2
        ;;
esac
